ARG ROS_DISTRO="jazzy"
FROM ros:$ROS_DISTRO

SHELL ["/bin/bash", "-lc"]

RUN apt-get update \
    && apt-get upgrade -y \
    && \
    : "remove cache" && \
    apt-get autoremove -y -qq && \
    apt install ros-$ROS_DISTRO-ros2-control ros-$ROS_DISTRO-ros2-controllers ros-$ROS_DISTRO-gz-ros2-control -y && \
    rm -rf /var/lib/apt/lists/*

# Install Gazebo
RUN apt-get update && apt-get install curl lsb-release gnupg libgl1 libglx0 mesa-utils -y && rm -rf /var/lib/apt/lists/*
RUN curl https://packages.osrfoundation.org/gazebo.gpg --output /usr/share/keyrings/pkgs-osrf-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/pkgs-osrf-archive-keyring.gpg] http://packages.osrfoundation.org/gazebo/ubuntu-stable $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/gazebo-stable.list > /dev/null \
    && apt-get update \
    && apt-get install gz-harmonic -y \
    && rm -rf /var/lib/apt/lists/*

# Install ROS dependencies
RUN apt-get update && apt-get install -y \
    ros-$ROS_DISTRO-spatio-temporal-voxel-layer \
    ros-$ROS_DISTRO-rqt-graph \
    ros-$ROS_DISTRO-perception-pcl \
    ros-$ROS_DISTRO-pcl-msgs \
    ros-$ROS_DISTRO-vision-opencv \
    ros-$ROS_DISTRO-plotjuggler-ros \
    ros-$ROS_DISTRO-rqt \
    ros-$ROS_DISTRO-rqt-common-plugins \
    ros-$ROS_DISTRO-rviz2 \
    ros-$ROS_DISTRO-joy \
    ros-$ROS_DISTRO-ur-description \
    ros-$ROS_DISTRO-ur-moveit-config \
    ros-$ROS_DISTRO-cv-bridge \
    libxcb-cursor0 \
    libxcb-cursor-dev \
    && rm -rf /var/lib/apt/lists/*

# Install other some dependencies
RUN apt-get update && apt-get install -y \
    libboost-all-dev \
    libtbb-dev \
    gdb \
    nano \
    python3-pip \
    python3.12-venv \
    clang-format \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /ws
RUN python3 -m venv .venv --system-site-packages \
    && source /ws/.venv/bin/activate \
    && pip3 install "numpy<2" ultralytics open3d opencv-python colcon-common-extensions pyransac3d lap

# Formatting tools
RUN source /ws/.venv/bin/activate \
    && pip install ruff

# Colors in terminal
RUN echo 'source /usr/lib/git-core/git-sh-prompt 2>/dev/null' >> ~/.bashrc && \
    echo "PROMPT_COMMAND='PS1_CMD1=\$(__git_ps1 \" (%s)\")'" >> ~/.bashrc && \
    echo 'export PS1="\[\033[01;32m\]\u@\H\[\033[00m\]:\[\033[01;34m\]\w\[\033[01;31m\]\${PS1_CMD1}\[\033[00m\]$ "' >> ~/.bashrc

# Shell setup
RUN echo "source /opt/ros/\$ROS_DISTRO/setup.bash" >> ~/.bashrc && \
    echo "if [ -f /other_ws/install/setup.bash ]; then source /other_ws/install/setup.bash; fi" >> ~/.bashrc && \
    echo "if [ -f /ws/install/setup.bash ]; then source /ws/install/setup.bash; fi" >> ~/.bashrc && \
    echo "source /ws/.venv/bin/activate" >> ~/.bashrc && \
    echo 'export PYTHONPATH="/ws/.venv/lib/python3.12/site-packages:$PYTHONPATH"' >> ~/.bashrc

WORKDIR /other_ws

RUN mkdir -p src && \
    git clone https://github.com/UniversalRobots/Universal_Robots_ROS2_GZ_Simulation.git -b ros2 src/ur_simulation_gz/ && \
    git clone https://github.com/PickNikRobotics/ros2_robotiq_gripper.git src/ros2_robotiq_gripper

RUN rm -rf src/ros2_robotiq_gripper/robotiq_driver \
    src/ros2_robotiq_gripper/robotiq_hardware_tests \
    src/ros2_robotiq_gripper/robotiq_driver_example

RUN apt-get update && \
    rosdep update && \
    rosdep install --from-paths src --ignore-src -y --rosdistro jazzy

RUN . /opt/ros/jazzy/setup.sh && \
    colcon build --symlink-install --packages-skip robotiq_driver

RUN echo "source /other_ws/install/setup.bash" >> ~/.bashrc

WORKDIR /ws

RUN mkdir src/ \
    && git clone -b feat/segmentation https://github.com/VisteK528/SWIZ.git src/ \
    && source /ws/.venv/bin/activate \
    && source /opt/ros/jazzy/setup.sh \
    && colcon build --symlink-install && source install/setup.bash

COPY .docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["bash"]